no-permission: "&c&lYou don't have permission to use this command!"
#supported placeholders: %player_name%, %gamemode%
game-mode-set-self: "&aYour gamemode is now &e%gamemode%"
game-mode-set-others-target: "&aYour gamemode is set to &e%gamemode% &aby &e%player_name%"
#supported placeholders: %target_name%, %gamemode%
game-mode-set-others-player: "&aYou have set &e%target_name% &agamemode to &e%gamemode%"
disabled-cmd-msg: "&c&lThe command you are trying to execute is disabled!"
fly:
  enabled: true
  fly-enable-msg: "&aFly mode is now &eENABLED"
  fly-disable-msg: "&aFly mode is now &eDISABLED"
  #supported placeholders: %target%
  fly-others-msg-player-disable: "&aYou have &eDISABLED &e%target% &afly"
  fly-others-msg-player-enable: "&aYou have &eENABLED &e%target% &afly"
  #supported placeholders: %player%
  fly-others-msg-target-enable: "&aYour fly is &eENABLED &aby &e%player%"
  fly-others-msg-target-disable: "&aYour fly is &eDISABLED &aby &e%player%"

kickall:
  enabled: true
  kick-msg: "&cYou have been kicked from the server!"

safe:
  execute-cmd-enabled: true
  kick-msg: "&cThe server is in maintenance/safe mode"

discord:
  enabled: true
  link: '&a Join our discord server now! = &bdiscord.gg'

welcome-title:
  enabled: false
  message: '&aWelcome To Server'
  messagesubtitle: '&bThanks for joining %player%'
welcome-bar:
  enabled: false
  message: '&awww.example.com'
suicide:
  enabled: true
  broadcast-message-enabled: true
  #supported placeholders: %player_name%
  broadcast-msg: "&c%player_name% &aTook there own life"
  player-message: "&aYou have killed yourself!"
clean:
  message: "&aYou have cleaned your inventory"
  #supported placeholders: %player_name%
  message-target: "&aYour inventory have been cleaned by &c%player_name%"
  #supported placeholders: %target_name%
  message-player: "&aYour have cleaned &c%target_name% &ainventory"
spawn:
  teleport-msg: "&aYou have teleported to spawn!"
  #supported placeholders: %player_name%
  teleport-others-msg-target: "&aYou have been teleported to spawn by &c%player_name%"
  #supported placeholders: %target_name%
  teleport-others-msg-player: "&aYou have teleported &c%target_name% &ato spawn"

#Don't change this
version: 1.10